function [Country,Month,Weekday,V,alphaX,betaX,gammaX,deltaX,alphaM,betaM,gammaM,deltaM,hours] = import_iberian_data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [COUNTRY,MONTH,WEEKDAY,V,ALPHAX,BETAX,GAMMAX,DELTAX,ALPHAM,BETAM,GAMMAM,DELTAM]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [COUNTRY,MONTH,WEEKDAY,V,ALPHAX,BETAX,GAMMAX,DELTAX,ALPHAM,BETAM,GAMMAM,DELTAM]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Country,Month,Weekday,V,alphaX,betaX,gammaX,deltaX,alphaM,betaM,gammaM,deltaM]
%   = importfile('parameters2.csv',1, 337);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/06/12 12:54:40

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%s%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Country = dataArray{:, 1};
Month = dataArray{:, 2};
Weekday = dataArray{:, 3};
V = dataArray{:, 4};
alphaX = dataArray{:, 5};
betaX = dataArray{:, 6};
gammaX = dataArray{:, 7};
deltaX = dataArray{:, 8};
alphaM = dataArray{:, 9};
betaM = dataArray{:, 10};
gammaM = dataArray{:, 11};
deltaM = dataArray{:, 12};
hours = dataArray{:, 13};

